import Head from "next/head";
import Navbar from "../components/Navbar";
import Started from "../components/Started";
import Services from "../components/Services";
import Cta from "../components/Cta";
import Team from "../components/Team";


export default function Home() {
  return(
    <div >
      <Head>
        <title>Eudaimonia</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Navbar/>
      <Started/>
      <Services/>
      <Team/>
      <Cta/>
    </div>
  ) 
}
